### ISSUE TITLE
Domain Name and DNS

### ISSUE THREAD

**Issue by joshunrau** [DouglasNeuroInformatics/PerfoMetadata#1]
We need to setup DNS with a proper domain name. @yassinebha can you choose a domain name (anything.douglasneuroinformatics.ca} and then @gdevenyi can set the DNS for this.

**Comment by yassinebha** [comment]
Yes, I would say PerfoMetadata.Douglasneuroinformatics.ca

**Comment by gdevenyi** [comment]
https://perfometadata.douglasneuroinformatics.ca/ configured, will be working in an hour or so.
